# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Go2webrpc < Formula
  desc "go2webrpc, Golang interface as your schema for client/server communication"
  homepage ""
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/golang-cz/go2webrpc/releases/download/v0.0.4/go2webrpc.darwin-arm64"
      sha256 "fef5b05deb5cc02be928286071b38eb26ffd938df5d5baca1af0acde54050493"

      def install
        bin.install "go2webrpc.darwin-arm64" => "go2webrpc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-cz/go2webrpc/releases/download/v0.0.4/go2webrpc.darwin-amd64"
      sha256 "9064d575fa1c8d3268670d5e81c5305ec97b1957ed14f13b4e99855bd2ffaede"

      def install
        bin.install "go2webrpc.darwin-amd64" => "go2webrpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/golang-cz/go2webrpc/releases/download/v0.0.4/go2webrpc.linux-amd64"
      sha256 "2e3dbe5388f3f8c1a91e7151d862a06cd8d5d3154cf8f04c270eb3ea646e8a58"

      def install
        bin.install "go2webrpc.linux-amd64" => "go2webrpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/golang-cz/go2webrpc/releases/download/v0.0.4/go2webrpc.linux-arm64"
      sha256 "3ac984d41e6309c6ba53ab1163708a9884e8e861b13c9f11ed7c9e1ad9e35444"

      def install
        bin.install "go2webrpc.linux-arm64" => "go2webrpc"
      end
    end
  end
end
