# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gospeak < Formula
  desc "gospeak, Golang interface as your schema for client/server communication"
  homepage ""
  version "0.7.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/golang-cz/gospeak/releases/download/v0.7.4/gospeak.darwin-amd64"
      sha256 "1dd06782363386a98844982470a1ca1a5944e46341fde122467107dd660eb0a1"

      def install
        bin.install "gospeak.darwin-amd64" => "gospeak"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/golang-cz/gospeak/releases/download/v0.7.4/gospeak.darwin-arm64"
      sha256 "c9566a8c21db4314d2abbebc06f87f5d460c002626203a68a41cbcaf3f9b8fd9"

      def install
        bin.install "gospeak.darwin-arm64" => "gospeak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/golang-cz/gospeak/releases/download/v0.7.4/gospeak.linux-amd64"
      sha256 "af6fb3807947041fdc4c3d186f62cde185ccfa7d37cf0661d6ce4337da1b254b"

      def install
        bin.install "gospeak.linux-amd64" => "gospeak"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/golang-cz/gospeak/releases/download/v0.7.4/gospeak.linux-arm64"
      sha256 "d881af9746f41ad48958861ce8ddf620fbcd69ab5083c16fd3b01d05c09cafb9"

      def install
        bin.install "gospeak.linux-arm64" => "gospeak"
      end
    end
  end
end
